"""
The shape catalogue and the piece that carries one.

Shapes are stored as sorted tuples of (col, row) offsets, normalised so the smallest column and
row are both zero. Normalising at construction is what lets the rest of the game compare shapes
for equality, look them up in a set, and treat a rotation as just another shape — no geometry
code anywhere else has to think about orientation.

Every shape is listed explicitly rather than generated by rotating a base set. That is deliberate:
a generator would produce all four rotations of every piece including the ones that make the game
worse (long diagonals, five-cell zigzags), and the balance of this genre lives in *which* shapes
exist. The list is the design.
"""

from __future__ import annotations

from dataclasses import dataclass, field


def normalise(cells) -> tuple:
    """Shift a set of offsets so its bounding box starts at the origin, and sort it."""
    cs = list(cells)
    mx = min(c for c, _ in cs)
    my = min(r for _, r in cs)
    return tuple(sorted((c - mx, r - my) for c, r in cs))


@dataclass(frozen=True)
class Shape:
    key: str
    cells: tuple
    #: Tier drives generation: 0 is trivially placeable, 3 is awkward. Difficulty raises the
    #: tiers on offer rather than inventing nastier shapes.
    tier: int
    w: int = field(init=False)
    h: int = field(init=False)

    def __post_init__(self):
        object.__setattr__(self, "w", max(c for c, _ in self.cells) + 1)
        object.__setattr__(self, "h", max(r for _, r in self.cells) + 1)

    @property
    def size(self) -> int:
        return len(self.cells)


def _shape(key: str, cells, tier: int) -> Shape:
    return Shape(key, normalise(cells), tier)


# Tier 0 — fits almost anywhere. These are the pieces that rescue a crowded board, and the
# generator leans on them when space runs short.
_T0 = (
    _shape("dot", [(0, 0)], 0),
    _shape("h2", [(0, 0), (1, 0)], 0),
    _shape("v2", [(0, 0), (0, 1)], 0),
    _shape("corner", [(0, 0), (1, 0), (0, 1)], 0),
    _shape("corner_r", [(0, 0), (1, 0), (1, 1)], 0),
    _shape("corner_b", [(0, 1), (1, 1), (1, 0)], 0),
    _shape("corner_l", [(0, 0), (0, 1), (1, 1)], 0),
)

# Tier 1 — the everyday pieces. Threes and the 2x2 square.
_T1 = (
    _shape("h3", [(0, 0), (1, 0), (2, 0)], 1),
    _shape("v3", [(0, 0), (0, 1), (0, 2)], 1),
    _shape("square", [(0, 0), (1, 0), (0, 1), (1, 1)], 1),
)

# Tier 2 — fours, the Ls and the Ts. Where the game starts asking for planning.
_T2 = (
    _shape("h4", [(0, 0), (1, 0), (2, 0), (3, 0)], 2),
    _shape("v4", [(0, 0), (0, 1), (0, 2), (0, 3)], 2),
    _shape("rect_h", [(0, 0), (1, 0), (2, 0), (0, 1), (1, 1), (2, 1)], 2),
    _shape("rect_v", [(0, 0), (1, 0), (0, 1), (1, 1), (0, 2), (1, 2)], 2),
    _shape("l_n", [(0, 0), (0, 1), (0, 2), (1, 2)], 2),
    _shape("l_e", [(0, 0), (0, 1), (1, 0), (2, 0)], 2),
    _shape("l_s", [(0, 0), (1, 0), (1, 1), (1, 2)], 2),
    _shape("l_w", [(0, 1), (1, 1), (2, 1), (2, 0)], 2),
    _shape("j_n", [(1, 0), (1, 1), (1, 2), (0, 2)], 2),
    _shape("j_e", [(0, 0), (1, 0), (2, 0), (2, 1)], 2),
    _shape("t_n", [(0, 0), (1, 0), (2, 0), (1, 1)], 2),
    _shape("t_s", [(1, 0), (0, 1), (1, 1), (2, 1)], 2),
    _shape("t_e", [(0, 0), (0, 1), (0, 2), (1, 1)], 2),
    _shape("t_w", [(1, 0), (1, 1), (1, 2), (0, 1)], 2),
)

# Tier 3 — the awkward ones. Fives, the plus, and the two short diagonals.
#
# The diagonals are two cells offset by one, not true three-cell diagonals: a real diagonal can
# never contribute to a line on its own and just clutters the board. These read as diagonal,
# place like a shape, and still help.
_T3 = (
    _shape("h5", [(0, 0), (1, 0), (2, 0), (3, 0), (4, 0)], 3),
    _shape("v5", [(0, 0), (0, 1), (0, 2), (0, 3), (0, 4)], 3),
    _shape("plus", [(1, 0), (0, 1), (1, 1), (2, 1), (1, 2)], 3),
    _shape("s_h", [(0, 1), (1, 1), (1, 0), (2, 0)], 3),
    _shape("z_h", [(0, 0), (1, 0), (1, 1), (2, 1)], 3),
    _shape("s_v", [(0, 0), (0, 1), (1, 1), (1, 2)], 3),
    _shape("z_v", [(1, 0), (1, 1), (0, 1), (0, 2)], 3),
    _shape("diag2", [(0, 0), (1, 1)], 3),
    _shape("diag2_b", [(1, 0), (0, 1)], 3),
    _shape("big_l", [(0, 0), (0, 1), (0, 2), (1, 2), (2, 2)], 3),
    _shape("big_j", [(2, 0), (2, 1), (2, 2), (1, 2), (0, 2)], 3),
)

SHAPES = _T0 + _T1 + _T2 + _T3
SHAPES_BY_TIER = (_T0, _T1, _T2, _T3)
SHAPES_BY_KEY = {s.key: s for s in SHAPES}

#: Sanity: normalisation must not have collapsed two entries into one key, and every shape must
#: fit the board. Checked at import because a duplicate key would silently shadow a shape.
assert len(SHAPES_BY_KEY) == len(SHAPES), "duplicate shape key"


class Piece:
    """One dealt piece: a shape, a colour index, and where it currently is on screen.

    The piece owns its own animation state — lift, return, and the little idle bob in the tray —
    because the alternative is the play scene holding three parallel lists of animation values
    and keeping them in step by hand.
    """

    __slots__ = ("shape", "color_index", "slot", "consumed",
                 "lift", "drag", "x", "y", "home_x", "home_y",
                 "return_t", "return_from", "bob")

    def __init__(self, shape: Shape, color_index: int, slot: int):
        self.shape = shape
        self.color_index = color_index
        self.slot = slot
        #: Set when the piece has been placed. Consumed pieces stay in the deal so the tray keeps
        #: its layout and the "all three used" test is a simple all().
        self.consumed = False

        self.lift = 0.0          # 0 in the tray, 1 fully picked up
        self.drag = False
        self.x = 0.0             # screen position of the shape's top-left cell
        self.y = 0.0
        self.home_x = 0.0        # resting position in the tray
        self.home_y = 0.0
        self.return_t = 0.0      # >0 while springing back after an illegal drop
        self.return_from = (0.0, 0.0)
        self.bob = 0.0           # phase offset so the three pieces do not bob in unison

    @property
    def cells(self) -> tuple:
        return self.shape.cells

    def __repr__(self) -> str:
        return f"<Piece {self.shape.key} c{self.color_index} slot{self.slot}>"
