#!/usr/bin/env node
/**
 * Publish playable games as a static site, for GitHub Pages or any CDN.
 *
 *   node tools/publish-web.mjs
 *
 * This works because a generated bundle is already completely static: `index.html` carries
 * the config inlined and `game.js` makes no network calls at all. That property exists so the
 * offline APK works, and it pays off a second time here — the same bytes that run inside an
 * APK also run from a plain file host, with no server, no database and no build step.
 *
 * Output layout:
 *
 *   docs/index.html            arcade page listing every game
 *   docs/engine/game.js        ONE copy of the engine, shared by every game
 *   docs/play/<slug>/index.html
 *   docs/embed/<slug>.html     bare page for iframing into another site
 *   docs/.nojekyll             stop Pages running Jekyll over it
 *
 * The engine is ~1.2 MB and byte-identical for every game, so it is emitted once and
 * referenced relatively. Copying it per game would be 8 MB of duplicates and would defeat
 * browser caching between games.
 */

import { mkdir, writeFile, readFile, copyFile, cp, rm, stat, access, readdir } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { planDeterministic } from '@forge/ai';
import { buildAnyGame } from '@forge/generation/genres';
import { bundleGame } from '@forge/bundler';
import { GENRE_REGISTRY, IMPLEMENTED_GENRES } from '@forge/schema/genres';
import { MIRROR_DIR, PYGBAG_VERSION } from './mirror-runtime.mjs';

const ROOT = resolve(import.meta.dirname, '..');
const OUT = join(ROOT, 'docs');
const TMP = join(ROOT, 'artifacts', '_publish');
/** Cover art, one 800x450 PNG per slug. Built by `python tools/make-thumbs.py`. */
const THUMBS = join(ROOT, 'assets', 'thumbs');
/** Installable builds, one signed APK per slug. Built by `node tools/build-apks.mjs`. */
const APKS = join(ROOT, 'assets', 'apk');

/** One showcase game per template, each with a distinct theme. */
const SHOWCASE = [
  { genre: 'rhythm_dash', prompt: 'neon cyberpunk city', blurb: 'One tap, one life. No menus — die and you are already running again.' },
  { genre: 'endless_runner', prompt: 'lava volcano depths', blurb: 'Auto-run and jump. Twenty levels, then endless mode.' },
  { genre: 'tap_to_fly', prompt: 'deep space station', blurb: 'Tap to flap and thread the gaps.' },
  { genre: 'snake', prompt: 'emerald jungle canopy', blurb: 'Eat, grow, and do not run into yourself.' },
  { genre: 'merge_2048', prompt: 'minimal monochrome ink', blurb: 'Swipe to merge tiles and reach the target.' },
  { genre: 'memory_match', prompt: 'pastel dessert land', blurb: 'Find every pair before the clock runs out.' },
  { genre: 'sliding_puzzle', prompt: 'arctic glacier', blurb: 'Slide the tiles back into order.' },
];

/**
 * Hand-built games that are not generated by the pipeline, published alongside it.
 *
 * NEON COIL is a Python/pygame game, so it cannot be bundled the way the Phaser templates are.
 * It is compiled to WebAssembly with pygbag, which produces a static folder that is simply
 * copied in — the same "no server, no build step at the far end" property the generated games
 * have. It is described here rather than dropped into docs/ by hand because publishing starts by
 * deleting docs/, so anything placed there manually disappears on the next run.
 */
const NATIVE_EXTRAS = [
  {
    slug: 'neon-coil',
    title: 'NEON COIL',
    label: 'Hand-built',
    /** Python compiled to WebAssembly: the APK has to carry a runtime the others do not. */
    wasm: true,
    family: 'arcade snake',
    from: join(ROOT, 'NeonCoil', 'build', 'web'),
    blurb: 'Free-steering snake with a body that traces real curves. Three modes, six power-ups, '
         + 'eight skins, and a combo chain worth playing for.',
    stats: 'Python + pygame, compiled to WebAssembly · zero asset files · 156 automated checks',
    note: 'First load fetches a ~10 MB engine runtime from this site, then the browser caches it.',
    palette: { bg: '#09081a', bgAccent: '#131130', ground: '#2a1155', player: '#00e8ff', obstacle: '#ff3ea5', accent: '#ffca40' },
    aspect: '16/9',
  },
  {
    slug: 'block-bloom',
    title: 'BLOCK BLOOM',
    label: 'Hand-built',
    wasm: true,
    family: 'block puzzle',
    from: join(ROOT, 'BlockBloom', 'build', 'web'),
    blurb: 'Drag blocks onto an 8x8 board and fill rows to clear them. Smart piece dealing that '
         + 'never hands you a dead board, escalating combos, ten objectives and five themes.',
    stats: 'Python + pygame, compiled to WebAssembly · zero asset files · 239 automated checks',
    note: 'First load fetches a ~10 MB engine runtime from this site, then the browser caches it.',
    palette: { bg: '#121628', bgAccent: '#1e2546', ground: '#2f3a68', player: '#5aaaff', obstacle: '#ff74a8', accent: '#ffce56' },
    // Portrait, so the embed snippet has to say so — a 9:16 game in a 16:9 box is a tall sliver
    // between two black bars.
    aspect: '9/16',
  },
  {
    slug: 'ivory-gambit',
    title: 'IVORY GAMBIT',
    label: 'Hand-built',
    family: 'chess',
    from: join(ROOT, 'IvoryGambit', 'build', 'web'),
    blurb: 'Full-rules chess with a real engine behind it — six difficulty levels, clocks, '
         + 'puzzles, six themes and a piece set drawn from code rather than downloaded.',
    stats: 'TypeScript + Canvas · 150 KB total · 186 automated checks including perft',
    // No runtime note: unlike the two Python games this is plain JavaScript and starts instantly,
    // which is worth saying on the card because the others need the caveat.
    note: 'Starts instantly — no runtime to download. Plays offline once loaded.',
    palette: { bg: '#1d1710', bgAccent: '#33261a', ground: '#4b3221', player: '#efdfc0', obstacle: '#a9784f', accent: '#e0a44a' },
    aspect: '16/9',
  },
  {
    slug: 'emberwake',
    title: 'EMBERWAKE',
    label: 'Hand-built',
    family: 'platform adventure',
    from: join(ROOT, 'Emberwake', 'build', 'web'),
    blurb: 'Ten levels across five worlds, with coyote time, jump buffering and a dash. '
         + 'Secrets, emberstones, seven enemy types and a boss at the end of the sky.',
    stats: 'TypeScript + Canvas · 118 KB total · every level proved completable by a solver',
    note: 'Starts instantly. Keyboard, touch and gamepad. Plays offline once loaded.',
    palette: { bg: '#140b1e', bgAccent: '#2a1b40', ground: '#7ec850', player: '#ff9b4a', obstacle: '#6f7f8c', accent: '#ffd27a' },
    aspect: '16/9',
  },
  {
    slug: 'feather-and-fetch',
    title: 'FEATHER & FETCH',
    label: 'Hand-built',
    family: 'duck shooting arcade',
    from: join(ROOT, 'FeatherFetch', 'build', 'web'),
    blurb: 'Aim, shoot, and let Biscuit do the fetching. Seven duck types, nine flight '
         + 'patterns, five environments and four modes — including Open Season, where the birds '
         + 'pile up in the grass until you call the harvester in.',
    stats: 'TypeScript + Canvas · 85 KB total · every duck proved fairly hittable by a sweep',
    note: 'Starts instantly. Mouse or touch. Plays offline once loaded.',
    palette: { bg: '#14210f', bgAccent: '#2a3f22', ground: '#5da84a', player: '#f0c04a', obstacle: '#8a5f36', accent: '#ffe08a' },
    aspect: '16/9',
  },
];

/**
 * The page a "GET APK" button lands on when someone wants to know what they just downloaded.
 *
 * Android will show a scary warning for any APK not installed from Play, and a player who has
 * never side-loaded anything will assume something is wrong and stop. So the page answers the
 * three questions that actually block an install, in the order they come up: is this safe, how
 * do I allow it, and what happens if it will not open.
 */
const installPage = (games) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Install on Android — Forge Arcade</title>
<meta name="description" content="Download any Forge game as an Android APK and play it offline." />
<style>
  :root{--bg:#0d0b14;--panel:#15121f;--line:rgba(255,255,255,.1);--text:#f2eefa;--muted:#a79fbe;--gold:#f0c04a}
  *{box-sizing:border-box;margin:0;padding:0}
  body{background:var(--bg);color:var(--text);font:15px/1.65 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;padding:38px 20px 70px}
  .wrap{max-width:760px;margin:0 auto}
  a{color:var(--gold)}
  h1{font-size:29px;letter-spacing:-.01em;margin-bottom:8px}
  h2{font-size:17px;margin:34px 0 10px}
  p{color:var(--muted);margin-bottom:12px}
  ol{color:var(--muted);margin:0 0 12px 20px}
  li{margin-bottom:7px}
  .back{display:inline-block;margin-bottom:26px;font-size:13px;text-decoration:none}
  .list{border:1px solid var(--line);border-radius:14px;overflow:hidden;margin-top:14px}
  .row{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:13px 16px;border-bottom:1px solid var(--line);background:var(--panel)}
  .row:last-child{border-bottom:0}
  .row b{font-weight:600;font-size:14px}
  .row a{font-size:12px;font-weight:600;text-decoration:none;border:1px solid rgba(240,192,74,.45);padding:7px 15px;border-radius:999px;white-space:nowrap}
  .note{border:1px solid var(--line);border-left:2px solid var(--gold);border-radius:0 12px 12px 0;background:var(--panel);padding:15px 18px;margin-top:22px;font-size:14px;color:var(--muted)}
  code{background:rgba(255,255,255,.07);padding:1px 6px;border-radius:5px;font-size:12.5px;color:var(--text)}
</style>
</head>
<body>
<div class="wrap">
  <a class="back" href="../">&larr; back to the arcade</a>
  <h1>Play these on your phone</h1>
  <p>Every game here is also a real Android app. Download it, install it, and it runs with no
     internet at all — the whole game is inside the file.</p>

  <h2>Installing</h2>
  <ol>
    <li>Tap a download below on the phone itself.</li>
    <li>Open it. Android will say the file came from an unknown source — this happens to every
        app not installed through the Play Store, including this one.</li>
    <li>Tap <b>Settings</b> in that prompt, turn on <b>Allow from this source</b>, then go back
        and tap <b>Install</b>.</li>
  </ol>
  <p>Android 7.0 or newer. Nothing else is needed.</p>

  <h2>Downloads</h2>
  <div class="list">
${games.map((g) => `
    <div class="row"><b>${esc(g.title)}</b><a href="${g.slug}.apk" download>APK</a></div>`).join('')}
  </div>

  <div class="note">
    <b>These apps ask for no permissions at all.</b> Not internet, not storage, not location —
    the install screen will show an empty list. That is not an oversight: the game is entirely
    self-contained, so there is nothing for it to ask for, and an empty permission list is the
    strongest proof of that we can give you.
  </div>

  <div class="note">
    <b>If it will not install.</b> "App not installed" almost always means an older build of the
    same game is already on the phone and was signed with a different key. Uninstall the old one
    first. On a work phone, side-loading may be blocked by policy and there is no way around
    that — the browser version plays the same game.
  </div>

  <footer style="margin-top:40px;font-size:12px;color:var(--muted);opacity:.6">
    &copy; 2026 Factorial Studio Private Limited.
  </footer>
</div>
</body>
</html>
`;

const slugify = (s) => String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);

console.log('\n\x1b[1mFORGE — publish static site\x1b[0m\n');

/**
 * Publishing wipes `docs/` and rebuilds it, which is what makes the output trustworthy — nothing
 * survives from a previous run to be quietly served forever.
 *
 * The APKs are the one exception, and they have to be. They take an Android SDK and several
 * minutes to produce, they are the only thing in `docs/` that is not cheap to regenerate, and
 * they are what the download buttons point at. Wiping them would mean anyone publishing the site
 * without an Android toolchain to hand would silently ship an arcade with no downloads and no
 * error to explain it.
 *
 * So they are carried across the wipe: rescued into `assets/apk/` first, then copied back in
 * below. Building new ones still wins, because `tools/build-apks.mjs` writes to that same
 * staging folder and this only fills in what is missing from it.
 */
try {
  const previous = await readdir(join(OUT, 'apk'));
  await mkdir(APKS, { recursive: true });
  const staged = new Set(await readdir(APKS).catch(() => []));
  let rescued = 0;
  for (const f of previous) {
    if (!f.endsWith('.apk') || staged.has(f)) continue;
    await copyFile(join(OUT, 'apk', f), join(APKS, f));
    rescued++;
  }
  if (rescued) console.log(`  ok   ${'Android'.padEnd(16)} kept ${rescued} APK(s) from the last publish`);
} catch { /* no previous publish, or it had no apk folder */ }

await rm(OUT, { recursive: true, force: true });
await mkdir(join(OUT, 'engine'), { recursive: true });
await mkdir(join(OUT, 'play'), { recursive: true });
await mkdir(join(OUT, 'embed'), { recursive: true });
// Pages runs Jekyll by default, which skips paths beginning with an underscore and slows
// every deploy down for no benefit here.
await writeFile(join(OUT, '.nojekyll'), '');

/**
 * The WebAssembly runtime the Python games need, served from our own site.
 *
 * It used to come from `pygame-web.github.io` — a free GitHub Pages site like this one, but not
 * ours. When it went down, both Python games stopped starting, which is not a dependency worth
 * having on a page someone is being shown. It is copied rather than linked because publishing
 * deletes `docs/` first, so the master copy lives in `vendor/` and lands here on every build.
 *
 * 21.9 MB on disk, about 10.5 MB over the wire once GitHub gzips it, against a 1 GB site limit.
 */
try {
  await access(MIRROR_DIR);
  await cp(MIRROR_DIR, join(OUT, 'engine-runtime'), { recursive: true });
  console.log(`  \x1b[32mok\x1b[0m   ${'Runtime'.padEnd(16)} ${'pygbag ' + PYGBAG_VERSION} `
              + `\x1b[2mengine-runtime/ (self-hosted)\x1b[0m`);
} catch {
  console.log(`  \x1b[33mskip\x1b[0m ${'Runtime'.padEnd(16)} not mirrored — the Python games will `
              + `fall back to pygame-web.github.io`);
  console.log(`       mirror it with:  node tools/mirror-runtime.mjs`);
}

/**
 * Cover art for the arcade cards.
 *
 * The cards used to be a flat gradient with four colour dots — the same shape for every game,
 * telling a visitor nothing about what they were about to play. These are real frames from the
 * real games, captured by driving each one and reading its canvas back (`tools/thumb-receiver.mjs`)
 * and composed by `tools/make-thumbs.py`.
 *
 * Missing covers are not an error: a slug with no PNG falls back to the old gradient card, so a
 * newly added game still publishes before anyone has captured a frame for it.
 */
const covers = new Set();
try {
  for (const f of await readdir(THUMBS)) {
    if (f.endsWith('.png')) covers.add(f.slice(0, -4));
  }
  await cp(THUMBS, join(OUT, 'thumb'), { recursive: true });
  console.log(`  \x1b[32mok\x1b[0m   ${'Covers'.padEnd(16)} ${String(covers.size).padStart(2)} images     `
              + `\x1b[2mthumb/\x1b[0m`);
} catch {
  console.log(`  \x1b[33mskip\x1b[0m ${'Covers'.padEnd(16)} none at assets/thumbs — cards fall back to gradients`);
  console.log(`       build them with:  python tools/make-thumbs.py`);
}

/**
 * Installable builds for the arcade cards.
 *
 * Same shape as the covers above and for the same reason: a missing APK is not an error. The
 * card simply loses its download button, so the site can be published on a machine with no
 * Android SDK and still be correct — it just offers fewer ways to play.
 *
 * This is why the APKs are staged in `assets/` rather than written straight into `docs/`:
 * publishing begins by deleting `docs/`, so anything built directly into it would vanish on the
 * next run, and the cards would have to guess at sizes they could no longer measure.
 */
const apks = new Map();
try {
  for (const f of await readdir(APKS)) {
    if (!f.endsWith('.apk')) continue;
    const { size } = await stat(join(APKS, f));
    apks.set(f.slice(0, -4), size);
  }
} catch { /* no APKs built — every card falls back to web-only */ }

if (apks.size) {
  await mkdir(join(OUT, 'apk'), { recursive: true });
  await cp(APKS, join(OUT, 'apk'), { recursive: true });
  console.log(`  [32mok[0m   ${'Android'.padEnd(16)} ${apks.size} APKs -> docs/apk/`);
} else {
  console.log(`  [33mskip[0m ${'Android'.padEnd(16)} none at assets/apk — cards will be web-only`);
  console.log(`       build them with:  node tools/build-apks.mjs`);
}

/**
 * A size a person can read at a glance.
 *
 * Rounding everything to megabytes printed the two smallest games as "0.0 MB", which reads as a
 * broken build rather than as a 46 KB one — and being that small is the most interesting thing
 * about them.
 */
const fileSize = (bytes) => bytes < 1024 * 1024
  ? `${Math.round(bytes / 1024)} KB`
  : `${(bytes / 1024 / 1024).toFixed(1)} MB`;

/** The download button, or nothing at all when this game has no build yet. */
const apkButton = (slug) => apks.has(slug)
  ? `<a class="btn ghost apk" href="apk/${slug}.apk" download
             title="Signed Android build — ${fileSize(apks.get(slug))}">GET APK <span>${fileSize(apks.get(slug))}</span></a>`
  : '';

/** A card's cover: the real screenshot when there is one, the palette gradient when there is not. */
const thumb = (g) => covers.has(g.slug)
  ? `<a class="thumb" href="play/${g.slug}/">
          <img src="thumb/${g.slug}.png" alt="${esc(g.title)} gameplay" width="800" height="450" loading="lazy" decoding="async" />
          <span class="playnow">PLAY</span>
        </a>`
  : `<a class="thumb flat" href="play/${g.slug}/"
           style="background:linear-gradient(150deg,${g.palette.bgAccent},${g.palette.bg})">
          <span class="sw"><i style="background:${g.palette.ground}"></i><i style="background:${g.palette.player}"></i><i style="background:${g.palette.obstacle}"></i><i style="background:${g.palette.accent}"></i></span>
          <span class="playnow">PLAY</span>
        </a>`;

const published = [];
let engineWritten = false;

for (const item of SHOWCASE) {
  if (!IMPLEMENTED_GENRES.includes(item.genre)) {
    console.log(`  \x1b[33mskip\x1b[0m ${item.genre} — not implemented`);
    continue;
  }
  const entry = GENRE_REGISTRY[item.genre];
  const { config } = planDeterministic(item.prompt, { genre: item.genre });
  const { levels, report, validation } = buildAnyGame(config);
  if (!report.ok || !validation.ok) {
    console.log(`  \x1b[31mfail\x1b[0m ${item.genre}: ${[...report.fatals, ...validation.curveIssues].join('; ')}`);
    continue;
  }

  const slug = slugify(`${entry.label}-${config.meta.title}`);
  const tmpDir = join(TMP, slug);
  await bundleGame({ config, levels, outDir: tmpDir });

  // Emit the engine exactly once.
  if (!engineWritten) {
    await copyFile(join(tmpDir, 'game.js'), join(OUT, 'engine', 'game.js'));
    engineWritten = true;
  }

  const html = await readFile(join(tmpDir, 'index.html'), 'utf8');
  const pageDir = join(OUT, 'play', slug);
  await mkdir(pageDir, { recursive: true });

  // Point at the shared engine, and switch telemetry off — there is no API behind a static
  // host, and a console full of failed POSTs is not what a client should see.
  const rewritten = html
    .replace('<script src="game.js"></script>', '<script src="../../engine/game.js"></script>')
    .replace('window.__GAME__ =', 'window.__FORGE_NO_TELEMETRY__ = true;\n      window.__GAME__ =');

  if (rewritten === html) {
    throw new Error(`could not rewrite the engine path for ${slug} — the bundler shell changed shape`);
  }
  await writeFile(join(pageDir, 'index.html'), rewritten, 'utf8');

  // A frameless variant for embedding, identical except it fills the iframe.
  await writeFile(
    join(OUT, 'embed', `${slug}.html`),
    rewritten.replace('</head>', '<style>#boot{font-size:11px}</style></head>'),
    'utf8'
  );

  published.push({
    slug,
    packageId: config.meta.packageId,
    label: entry.label,
    family: entry.family,
    title: config.meta.title,
    tagline: config.meta.tagline,
    blurb: item.blurb,
    palette: config.theme.palette,
    levels: report.levelsBuilt,
    elements: report.totalObstacles,
    minutes: report.estTotalMinutes,
  });
  console.log(`  \x1b[32mok\x1b[0m   ${entry.label.padEnd(16)} ${config.meta.title.padEnd(16)} play/${slug}/`);
}

if (!published.length) throw new Error('nothing published');

// ── hand-built extras ───────────────────────────────────────────────────────
const extras = [];
for (const x of NATIVE_EXTRAS) {
  try {
    await access(join(x.from, 'index.html'));
  } catch {
    // Not built. Skip it with a loud note rather than emitting a card that 404s — a dead link
    // on the arcade page is worse than a missing one.
    console.log(`  [33mskip[0m ${x.title.padEnd(16)} no web build at ${x.from}`);
    console.log(`       build it with:  npm run publish:${x.slug.replace(/-/g, '')}`);
    continue;
  }
  const dest = join(OUT, 'play', x.slug);
  await cp(x.from, dest, { recursive: true });

  /**
   * An embed page, so a hand-built game can be dropped into another site the same way the
   * generated ones are.
   *
   * A wrapper around an iframe rather than a copy of the game's own page: the WebAssembly
   * loader resolves its archive relatively, so a duplicated page two directories away would
   * ask for files that are not there. One level of nesting is the cheap, correct answer.
   *
   * `allow` matters. The runtime wants autoplay for its audio context and fullscreen for the
   * button in its own chrome, and an iframe without them gets a game with no sound.
   */
  await writeFile(join(OUT, 'embed', `${x.slug}.html`), `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${esc(x.title)}</title>
<style>
  html,body{margin:0;padding:0;height:100%;background:${x.palette.bg};overflow:hidden}
  iframe{display:block;width:100%;height:100%;border:0}
</style>
</head>
<body>
<iframe src="../play/${x.slug}/" title="${esc(x.title)}"
        allow="autoplay; fullscreen; gamepad; cross-origin-isolated"
        allowfullscreen></iframe>
</body>
</html>
`, 'utf8');

  extras.push(x);
  console.log(`  [32mok[0m   ${x.label.padEnd(16)} ${x.title.padEnd(16)} play/${x.slug}/`);
}

// ── arcade index ────────────────────────────────────────────────────────────

const extraCards = extras
  .map(
    (g) => `
      <article class="card">
        ${thumb(g)}
        <div class="body">
          <h3>${esc(g.title)}</h3>
          <p class="fam">${esc(g.label)} · ${esc(g.family)}</p>
          <p class="blurb">${esc(g.blurb)}</p>
          <p class="stats">${esc(g.stats)}</p>
          <p class="stats" style="color:var(--gold);opacity:.9">${esc(g.note)}</p>
          <a class="btn" href="play/${g.slug}/">PLAY NOW</a>
          ${apkButton(g.slug)}
          <a class="btn ghost" href="embed/${g.slug}.html">EMBED</a>
        </div>
      </article>`
  )
  .join('');

const cards = published
  .map(
    (g) => `
      <article class="card">
        ${thumb(g)}
        <div class="body">
          <h3>${esc(g.title)}</h3>
          <p class="fam">${esc(g.label)} · ${esc(g.family)}</p>
          <p class="blurb">${esc(g.blurb)}</p>
          <p class="stats">${g.levels} levels · ${g.elements} elements verified · ~${g.minutes} min</p>
          <a class="btn" href="play/${g.slug}/">PLAY NOW</a>
          ${apkButton(g.slug)}
        </div>
      </article>`
  )
  .join('');

const index = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Forge Arcade — generated games by Factorial Studio</title>
<meta name="description" content="Playable games generated by Forge. Every level is verified finishable before it ships." />
<meta property="og:title" content="Forge Arcade — generated games" />
<meta property="og:description" content="Every one of these was generated from a single line of text. Every level is proven finishable." />
${covers.has('neon-coil') ? `<meta property="og:image" content="thumb/neon-coil.png" />
<meta name="twitter:card" content="summary_large_image" />` : ''}
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Bungee&family=Fredoka:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
<style>
  :root{--ink:#06281c;--g800:#0a5a42;--leaf:#7cb342;--leaf2:#a3d977;--gold:#fbbf24;--orange:#ff7043;--text:#eaf5ee;--muted:#a9c6b5;--f-disp:'Bungee',cursive;--f-body:'Fredoka',sans-serif;--r:22px;--line:rgba(255,255,255,.08)}
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:var(--f-body);background:var(--ink);color:var(--text);line-height:1.55;
    background-image:radial-gradient(1100px 520px at 78% -12%,rgba(124,179,66,.16),transparent 60%),radial-gradient(760px 420px at 6% 108%,rgba(251,191,36,.1),transparent 62%);
    background-attachment:fixed;-webkit-font-smoothing:antialiased}
  .wrap{max-width:1180px;margin:0 auto;padding:26px 20px 80px}
  .logo{font-family:var(--f-disp);font-size:19px;color:var(--text);text-decoration:none}
  .logo span{color:var(--leaf2)}
  h1{font-family:var(--f-disp);font-size:clamp(28px,5vw,46px);line-height:1.06;margin:20px 0 10px}
  .sub{color:var(--muted);font-size:15px;max-width:66ch;margin-bottom:8px}
  .pill{display:inline-block;font-size:11px;padding:5px 12px;border-radius:999px;background:rgba(255,255,255,.07);color:var(--muted);border:1px solid var(--line)}
  .pill.live{color:var(--leaf2);border-color:rgba(163,217,119,.35)}
  h2{font-family:var(--f-disp);font-size:14px;letter-spacing:.6px;color:var(--muted);margin:38px 0 16px}
  .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:18px}
  .card{border-radius:var(--r);overflow:hidden;border:1px solid var(--line);background:rgba(0,0,0,.24)}
  .thumb{display:block;position:relative;aspect-ratio:16/9;overflow:hidden;text-decoration:none;background:#000}
  .thumb img{display:block;width:100%;height:100%;object-fit:cover;transition:transform .35s ease}
  .card:hover .thumb img{transform:scale(1.04)}
  /* A soft floor under the badge, so PLAY stays readable over a bright frame. */
  .thumb::after{content:'';position:absolute;inset:auto 0 0 0;height:56%;pointer-events:none;
    background:linear-gradient(transparent,rgba(0,0,0,.62))}
  .thumb.flat{display:flex;align-items:flex-end;justify-content:space-between;padding:12px}
  .sw{display:flex;gap:5px;position:relative;z-index:1}
  .sw i{width:22px;height:22px;border-radius:6px;display:block}
  .playnow{font-family:var(--f-disp);font-size:12px;color:#24160a;background:var(--gold);padding:6px 12px;border-radius:999px;
    position:absolute;left:12px;bottom:12px;z-index:1}
  .thumb.flat .playnow{position:static}
  .body{padding:15px 16px 18px}
  .body h3{font-family:var(--f-disp);font-size:16px}
  .fam{font-size:11px;color:var(--leaf2);text-transform:uppercase;letter-spacing:.5px;margin:3px 0 8px}
  .blurb{font-size:13px;color:var(--muted);margin-bottom:8px}
  .stats{font-size:11px;color:var(--muted);opacity:.75;margin-bottom:13px}
  .btn{display:inline-block;font-weight:600;font-size:13px;padding:11px 22px;border-radius:999px;background:var(--gold);color:#24160a;text-decoration:none}
  .btn:hover{transform:translateY(-1px)}
  .btn.ghost{background:transparent;color:var(--muted);border:1px solid var(--line);margin-left:8px}
  .btn.ghost:hover{color:var(--text);border-color:rgba(255,255,255,.22)}
  /* Cards carry up to three buttons now, and at 280px they have to be allowed to wrap. */
  .btn{margin-top:6px}
  .btn.apk{border-color:rgba(240,192,74,.5);color:var(--gold)}
  .btn.apk:hover{color:#ffe08a;border-color:rgba(240,192,74,.9);background:rgba(240,192,74,.08)}
  .btn.apk span{opacity:.6;font-weight:400;margin-left:5px}
  .note{margin-top:18px;padding:16px 18px;border-radius:var(--r);background:rgba(255,255,255,.05);border:1px solid var(--line);font-size:13.5px;color:var(--muted)}
  code{font-family:ui-monospace,Consolas,monospace;font-size:12px;background:rgba(0,0,0,.35);padding:2px 6px;border-radius:5px;color:var(--leaf2)}
  pre{margin-top:10px;padding:14px;border-radius:14px;background:rgba(0,0,0,.4);overflow-x:auto;font-size:12px;color:var(--text)}
  footer{margin-top:52px;padding-top:22px;border-top:1px solid var(--line);font-size:12px;color:var(--muted)}
</style>
</head>
<body>
<div class="wrap">
  <a class="logo" href="/">FACTORIAL<span>STUDIO</span></a>
  <h1>FORGE ARCADE</h1>
  <p class="sub">
    The templates below were generated from a single line of text — layout, difficulty curve,
    palette, sound and all — and each exports as a signed Android APK that runs with no
    internet. The hand-built games are here for contrast: same studio, same art-from-code
    approach, no generator in front of it. Two are Python compiled to WebAssembly; IVORY GAMBIT
    is TypeScript, and its whole chess engine — board, rules, search — fits in 150 KB.
  </p>
  <p><span class="pill live">${published.length} TEMPLATES</span>${extras.length ? ` <span class="pill live">${extras.length} HAND-BUILT</span>` : ''} <span class="pill">EVERY LEVEL VERIFIED FINISHABLE</span> <span class="pill">NO PLUGINS</span></p>

  <h2>PLAY</h2>
  <div class="grid">${extraCards}${cards}
  </div>

  <div class="note">
    <b>Embedding these on another page.</b> Every game here has a frameless version made for
    iframes, so it plays inside your own page instead of navigating away from it:
    <pre>&lt;iframe src="https://fojiphoto.github.io/AIGameGen/embed/${published[0].slug}.html"
        style="width:100%;aspect-ratio:900/506;border:0;border-radius:14px"
        title="${esc(published[0].title)}"&gt;&lt;/iframe&gt;</pre>
${extras.length ? `    The WebAssembly ones need the two <code>allow</code> permissions, without which they load
    but stay silent, and each wants a box of its own shape:
${extras.map((x) => `    <pre>&lt;iframe src="https://fojiphoto.github.io/AIGameGen/embed/${x.slug}.html"
        style="width:100%;aspect-ratio:${x.aspect || '16/9'};border:0;border-radius:14px"
        allow="autoplay; fullscreen" allowfullscreen
        title="${esc(x.title)}"&gt;&lt;/iframe&gt;</pre>`).join('\n')}` : ''}
  </div>

  <div class="note">
    <b>Why "verified finishable" is the interesting part.</b> Levels are generated
    procedurally, then each one is simulated headlessly before it ships — jump arcs, gap
    reachability, landing room, move budgets. A level that cannot be completed is re-seeded
    until it can be. Nothing here was hand-placed, and nothing here is impossible.
  </div>

  <footer>© 2026 Factorial Studio Private Limited. Generated with Forge.</footer>
</div>
</body>
</html>
`;

await writeFile(join(OUT, 'index.html'), index, 'utf8');

/**
 * A machine-readable list of everything published, written for `tools/build-apks.mjs`.
 *
 * The APK builder needs a title, a package id, a palette for the launcher icon and an
 * orientation for each game. It could import the generator and recompute all of that, but then
 * two tools would be deriving the same facts by two routes and would eventually disagree —
 * an APK whose icon or package id did not match the game on the site. Publishing already knows
 * every one of these, so it writes them down and the builder reads them.
 *
 * `orientation` is the one value that is not simply copied through: the site expresses shape as
 * a CSS aspect ratio, and Android wants a screenOrientation, so the taller-than-wide ones become
 * portrait here rather than in the builder.
 */
const manifest = [
  ...extras.map((x) => {
    const [w, h] = String(x.aspect || '16/9').split('/').map(Number);
    return {
      slug: x.slug,
      title: x.title,
      kind: x.wasm ? 'wasm' : 'native',
      packageId: `com.factorialstudio.${x.slug.replace(/-/g, '')}`,
      palette: x.palette,
      orientation: h > w ? 'sensorPortrait' : 'sensorLandscape',
    };
  }),
  ...published.map((g) => ({
    slug: g.slug,
    title: g.title,
    kind: 'generated',
    packageId: g.packageId,
    palette: g.palette,
    orientation: 'sensorLandscape',
  })),
];
await writeFile(join(OUT, 'games.json'), JSON.stringify(manifest, null, 2), 'utf8');

// The install page. Written after the APK copy above, so it survives it.
if (apks.size) await writeFile(join(OUT, 'apk', 'index.html'), installPage(manifest), 'utf8');

await rm(TMP, { recursive: true, force: true });

const engineSize = (await stat(join(OUT, 'engine', 'game.js'))).size;
console.log(`\n\x1b[32m✓ published ${published.length} generated + ${extras.length} hand-built\x1b[0m`);
console.log(`  output   docs/`);
console.log(`  engine   ${(engineSize / 1024 / 1024).toFixed(2)} MB (shared by all games)`);
console.log(`\n  Once GitHub Pages is enabled for the repo (Settings → Pages → main / docs):`);
console.log(`    arcade  https://fojiphoto.github.io/AIGameGen/`);
for (const x of extras) {
  console.log(`    ${x.title.padEnd(16)} https://fojiphoto.github.io/AIGameGen/play/${x.slug}/`);
}
for (const g of published) {
  console.log(`    ${g.label.padEnd(16)} https://fojiphoto.github.io/AIGameGen/play/${g.slug}/`);
}
console.log('');
